version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flask_app
      - SECRET_KEY=dev-key
    volumes:
      - .:/app

  frontend:
    build: 
      context: ./taskmanager
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: 